kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: recipe
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhR0Z1YzIxMVoyVnNPbWRvY0Y5RGVuSnBiME5hVlhNM00xRnFZMmh1ZGtSVmJERlRVMEpyYXpaQ05Wa3daRGhtUm04In19fQ0K