name: Release Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Updated to latest version
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3  # Updated to latest version
        with:
          version: v3.8.1

      - name: Print Latest Tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          echo "Latest tag: $latest_tag"
          echo "Changes since the latest tag:"
          git diff $latest_tag HEAD --name-only

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts/recipe/charts
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Debug Chart Changes
        run: |
          echo "Listing changed files in 'charts/recipe/charts' directory:"
          git diff --name-only HEAD~1 HEAD -- charts/recipe/charts/
          echo "End of changed files."
