name: Continuous Integration and Testing

# @date: 04.04.2024
# @authors: Philipp Schrefel, Andreas Mittendorfer

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'ghcr.io/hansmugel/sdx_uebung:latest'
  IMAGE_TAG: latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# JOBS
jobs:
  # LINTING

  lint-dockerfile:
    name: Lint Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List directory contents
        run: ls -la

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.6.0
        with:
          dockerfile: dockerfile

  lint-source:
    needs: lint-dockerfile
    name: Lint Source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: src

      - name: Run golangci-lint
        run: |
          cd src
          golangci-lint run


  # BUILD
  build-test:
    needs: lint-source
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfile
          tags: 'ghcr.io/hansmugel/sdx_uebung:latest'
          load: true

      - name: Scan the Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/hansmugel/sdx_uebung:latest'
          format: 'table'

      - name: Start Application
        run: docker-compose up -d

      - name: Installation of PyPy
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy-3.10'

        
      - name: Install Dependencies and Run Test Script with Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: |
          pip install requests
          python ${{ github.workspace }}/testeroni.py

  push-to-registry:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'ghcr.io/hansmugel/sdx_uebung:latest'
          platforms: linux/amd64,linux/arm64


